# Generated by Django 2.0.6 on 2019-02-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0002_newaccounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newAccounts',
        ),
    ]
